name: Run CBB Money Scraper

on:
  workflow_dispatch:  # allows manual trigger from the Actions tab
  #schedule: # DONT NEED IT TO BE ON A SCHEDULE UNTIL IN SEASON
    #- cron: "0 6 * * *"  # optional: runs every day at 6 AM UTC
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # allow up to 6 hours (GitHub’s max for free tier)

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas sqlalchemy mysql-connector-python python-dotenv lxml html5lib

      # Step 4: Create .env file from GitHub secrets (FOR MYSQL IF WANTED LATER, NOT NEEDED RIGHT NOW AS I SAVE THE FILES INTO THE REPO)
      #- name: Create .env file
      #  run: |
      #    echo "DB_USER=${{ secrets.DB_USER }}" >> .env
      #    echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
      #    echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
      #    echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env

      # Step 5: Run your scraper
      - name: Run scraping orchestrator
        run: |
          python -m Scraping.run_all_scrapes --start 2022 --end 2025

      # Step 6: Upload CSV outputs (optional)
      - name: Upload scraped CSVs
        uses: actions/upload-artifact@v4
        with:
          name: scraped-data
          path: |
            DataFrames/**
            
      # Step 7: Commit and push updated CSVs back to repo
      - name: Commit and push new data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add DataFrames/**/*.csv
          git commit -m "Auto-update scraped data ($(date +'%Y-%m-%d %H:%M:%S'))" || echo "No changes to commit"
          git push


